### ISSUE TITLE
How about go-app ?

### ISSUE THREAD

**Issue by linkerlin** [xyproto/algernon#101]
https://go-app.dev/
Integrate go-app to algernon wil make algernon to be a out-of-box tool for building a PWA.

**Comment by scrumit** [comment]
Yes, it is a bit of a sledgehammer to crack a nut. 

go-app.dev generates a PWA page and so it really only needs Algernon to serve the page. The rest, I guess, can be done just with Go.

**Comment by xyproto** [comment]
`go-app` looks really cool.

My first thought was that all the functions could be wrapped as Lua functions, for Algernon, but then I see `GOARCH=wasm GOOS=js go build -o web/app.wasm` on the web page. It looks to me like they only target developers that compile Go to WASM.

Unless I've misunderstood how this works, a full Go compiler would be needed as a dependency for Algernon in order to support `go-app`, which is a bit much.

**Comment by xyproto** [comment]
Please add comments to this issue if good ways of integrating with go-app springs to mind.

**Comment by scrumit** [comment]
When I installed algernon the first step was to install go. I think you mean once built algernon doesn't need the go compiler.

**Comment by xyproto** [comment]
Yes, as a runtime dependency.
