### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by ogoudron** [xyproto/algernon#20]
Hello,
Do you plan to support Let's Encrypt certificats for HTTPS ?

**Comment by xyproto** [comment]
Hello, yes.

Currently, using Let's Encrypt certificates with Algernon works great, but you might want to use a cron job to restart Algernon once every month (or how often the Let's Encrypt certificates are refreshed by the Let's Encrypt service).

I wrote a short snippet about how to use Algernon and Let's Encrypt here: https://github.com/xyproto/algernon#https-certificates-with-lets-encrypt-and-algernon

I'm planning to add built-in support for refreshing Let's Encrypt certificates from within Algernon, to make this a bit smoother.

**Comment by xyproto** [comment]
I'm planning to implement this feature using the certmagic package:

https://github.com/mholt/certmagic

**Comment by mholt** [comment]
@xyproto Cool, let me know how it goes!

**Comment by ogoudron** [comment]
Hello, do you have some news to share about this issue?

**Comment by xyproto** [comment]
I looked into this, but it looks like adding Let's Encrypt support (at least the method I looked into) requires replacing both the HTTP and HTTP/2 handler in one go (no pun intended).

I wish to rewrite the server-setup part, so that:

* The HTTP handling is done by a fast third party module, like [gnet](https://github.com/panjf2000/gnet).
* The HTTP handler is redirecting to HTTP/2 or QUIC (the `https://` address), by default. Some of the "detect if your webpage is secure" pages online has this is a requirement.
* Maybe drop QUIC support altogether, because it is a hindrance for compiling with both `gccgo` and earlier (but commonly used) versions of Go, like version `1.11`.

In the same rewrite, I would like to use the `certmagic` module (which is amazingly nice and easy to set up if it takes over both the HTTP and HTTP/2 setup, but I found it a bit more involved when integrating with QUIC and modules that handle graceful shutdown and rate limiting). Maybe it's really easy and I just approached the integration from the wrong angle.

**Comment by mholt** [comment]
@xyproto If you have the advanced use case, you can configure your own TLS listener and HTTP handler with just a few more lines of code: https://github.com/mholt/certmagic#advanced-use

You can either have CertMagic do all the HTTP/HTTPS stuff for you, or you can get a TLS config from it, or a TLS listener from it, or you can wire up both the TLS + HTTP stuff yourself as that link demonstrates. So, there's various levels of abstraction and you can choose which level you need.

But yeah, I highly recommend the use of CertMagic for TLS stuff, since it does more than just cert renewal. It also takes care of OCSP stapling and even handles the case when certificates are revoked, etc.

**Comment by xyproto** [comment]
I've thought about this, and I would like to keep the current separation of concerns, where Algernon only deals with the certificates that are given, and not communicates directly with Let's Encrypt. This also makes Algernon independent from any issues or changes that Let's Encrypt might go through in the future.

On my personal web server, I use Let's Encrypt together with Algernon, but without built-in support for Let's Encrypt inside Algernon.

I'm planning to set up a mail server as well, and if I haven't misunderstood, the same certificates can be re-used for the mail server.

I like the idea of the certificates being independent.

@mholt Nice work with Caddy and CertMagic, though!
