### ISSUE TITLE
Modularizing project

### ISSUE THREAD

**Issue by iMaxopoly** [xyproto/algernon#4]
Hi,

Very interesting project.

I see the focus tends to be towards lua, but what if I don't wish to use lua?

Second thing I wish to bring to your notice is that fasthttp is probably better than net/http so maybe you could migrate to that?

Regards :)

**Comment by xyproto** [comment]
Hi,

Included with Algeron, is support for writing plugins in almost any language (that supports JSON-RPC and base64 encoding). Example plugins for Python and Go are included in the `plugins` folder.

It's also possible to use a language like [Moonscript](http://moonscript.org/), for writing the code in a different language and then compile to Lua.

In addition to this, there is a Lua function called `py` that makes it really easy to call Python scripts. There is an example of this [here](https://github.com/xyproto/algernon/tree/master/samples/simplepy).

If you were thinking of a different language than Lua (and not Moonscript/Python/Go), which language did you have in mind?

I will look into fasthttp!

Thanks for your interest in Algernon.

Best regards

**Comment by kryptodev** [comment]
Hi, thanks for replying.

I was planning on experimenting with just Go language using your framework.
You have quite an elaborate setup here, makes me wonder why so few stars.

It would be preferable if you had some benchmarks done. I just had a conflict(mostly because I'm a bad reader) regarding your lua modules, if they might end up slowing down the server's performance if I choose to write code in golang itself. Basically I wondered if, at the end of the compilation process, the binary that is created would only consist of things that I have used and not the whole lua/python bindings that I haven't used. Pardon me for my ignorance because I haven't used your framework yet.

It just looks like such an eyecandy I had to ask before I tried xD

Thanks for considering fasthttp, it's one of the things making golang shine.

Regards :)

**Comment by xyproto** [comment]
I just discovered that [fasthttp doesn't support HTTP/2](https://github.com/valyala/fasthttp#faq). This makes it less interesting, but I might add it just for when serving regular HTTP.

Note that Algernon isn't a framework for Go, but a web/application server.

The speed should be pretty good, since many responses can be served directly from the cache (without compressing with gzip, the cache is already compressed) and since HTTP/2 is used. I am planning on adding some benchmark stats to the front page, eventually.

**Comment by xyproto** [comment]
`fasthttp` was hard to combine with `flush()`, so after having added in `fasthttp` for a while, I removed it.

Algernon now uses https://github.com/julienschmidt/httprouter, though, which should also improve performance.
